with base as (
    select
        source_key,
        id,
        cnh,
        cnpj,
        cpf,
        emissor_rg,
        nome,
        outro_doc,
        rg,
        tipo_outro_doc,
        uf_cnh_id,
        categoria_cnh,
        situacao_cnh,
        validade_cnh,
        data_nascimento,
        data_primeira_cnh,
        data_validade_cnh,
        endereco,
        telefone,
        uf_rg_id,
        sexo,
        email,
        situacao_habilitacao
    from {{ ref('stg_pessoa') }}
)

select
    row_number() over (order by source_key, id) as sk_pessoa,
    source_key,
    id,
    cnh,
    cnpj,
    cpf,
    emissor_rg,
    nome,
    outro_doc,
    rg,
    tipo_outro_doc,
    uf_cnh_id,
    categoria_cnh,
    situacao_cnh,
    validade_cnh,
    data_nascimento,
    data_primeira_cnh,
    data_validade_cnh,
    endereco,
    telefone,
    uf_rg_id,
    sexo,
    email,
    situacao_habilitacao
from base

union all

select
    0 as sk_pessoa,
    null as source_key,
    0 as id,
    null as cnh,
    null as cnpj,
    null as cpf,
    null as emissor_rg,
    'Não Informado' as nome,
    null as outro_doc,
    null as rg,
    null as tipo_outro_doc,
    null as uf_cnh_id,
    null as categoria_cnh,
    null as situacao_cnh,
    null as validade_cnh,
    null as data_nascimento,
    null as data_primeira_cnh,
    null as data_validade_cnh,
    null as endereco,
    null as telefone,
    null as uf_rg_id,
    null as sexo,
    null as email,
    null as situacao_habilitacao
